name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build
        run: JEKYLL_ENV=production bundle exec jekyll build
      
      - name: Upload site
        uses: actions/upload-artifact@v2.1.4
        with:
          name: site
          path: _site/*
          if-no-files-found: error
          
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: clone publish site
        run: |
          git clone https://.:${{ secrets.PUBLISHKEY }}@github.com/jason-kerney/jason-kerney.github.io.git
      - name: Remove old items
        run: |
          cd ./jason-kerney.github.io
          rm ./20* -f -r
          rm ./about -f -r
          rm ./archives -f -r
          rm ./assets -f -r
          rm ./categories -f -r
          rm ./norobots -f -r
          rm ./now -f -r
          rm ./page* -f -r
          rm ./posts -f -r
          rm ./series -f -r
          rm ./tags -f -r
          rm ./404.html -f
          rm ./app.js -f
          rm ./feed.xml -f
          rm ./index.html -f
          rm ./redirects.json -f
          rm ./robots.txt -f
          rm ./sitemap.xml -f
          rm ./sw.js -f
      - name: Download site
        uses: actions/download-artifact@v2.0.5
        with:
          name: site
          path: .
      - name: List
        run: ls
          
