name: Jekyll site CI/CD

on:
  schedule:
    - cron: "5 8 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      
      - name: Set up cache
        uses: actions/cache@v3.2.6
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.144.2
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build
        run: JEKYLL_ENV=production bundle exec jekyll build
      
      - name: Upload site
        uses: actions/upload-artifact@v3.1.2
        with:
          name: site
          path: _site/*
          if-no-files-found: error
          
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: clone publish site
        run: |
          git clone https://.:${{ secrets.PUBLISHKEY }}@github.com/jason-kerney/jason-kerney.github.io.git
      - name: Remove old items
        run: |
          cd ./jason-kerney.github.io
          rm ./20* -f -r
          rm ./about -f -r
          rm ./archives -f -r
          rm ./assets -f -r
          rm ./categories -f -r
          rm ./norobots -f -r
          rm ./now -f -r
          rm ./page* -f -r
          rm ./posts -f -r
          rm ./series -f -r
          rm ./tags -f -r
          rm ./*.html -f
          rm ./*.js -f
          rm ./*.xml -f
          rm ./*.json -f
          rm ./*.txt -f
      - name: Download site
        uses: actions/download-artifact@v3.0.2
        with:
          name: site
          path: jason-kerney.github.io
      - name: Push
        run: |
          cd ./jason-kerney.github.io
          ls
          git config --global user.email "jason@teamkerney.com"
          git config --global user.name "jason-kerney"
          git add .
          git diff-index --quiet HEAD || git commit -m "Automatic publish from github.com/jason-kerney/blog"
          git push origin main
